# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: ja-JP

reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  path_filters:
    - "!**/*.lock"
    - "!**/package-lock.json"
    - "!**/.next/**"
    - "!**/node_modules/**"
  path_instructions:
    - path: "**/*.tsx"
      instructions: "Reactコンポーネントのベストプラクティス、hooks の使い方、パフォーマンスに注目してレビューしてください"
    - path: "**/*.ts"
      instructions: "TypeScriptの型安全性とエラーハンドリングに注目してレビューしてください"
    - path: "app/**"
      instructions: "Next.js App Routerのパターンに従っているか確認してください"

chat:
  auto_reply: true
